# Basic
title = "Damian Ryś"
baseURL = "https://damiry0.github.io/"
theme = "vno-hugo"

# Pagination
paginate = 10
paginatePath = "page"

[outputs]
  home = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "Projects"
    identifier = "projects"
    url = "https://github.com/Damiry0?tab=repositories"
    weight = 10

[taxonomies]
    tag = "tags"
    
[params]
author = "onevcat"
subtitle = "Salam alejkum"
description = """Student trzeciego roku Automatyki i Robotyki. 
 Btw I use Arch."""
welcomeMessage = "Poniżej znajdziesz gdzie mnie znaleść:"

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
coverColor = "clear"

[params.comment]
disqus = "vno-hugo"
duoshuo = ""

# Take a look on https://github.com/gitalk/gitalk#usage for more info.
[params.comment.gitalk]
ID = ""
secret = ""
repo = ""
owner = ""

[params.social]
github = "damiry0"
linkedin = "damianrys"
mail = "damian.rys0@gmail.com"

[params.ga]
ID = "your_ga_id"
host = "your_host"

# The blog button should not be removed.
[params.blogButton]
title = "Blog"
description = "Visit blog"

[permalinks]
posts = "/:year/:month/:title/"
